"""
Constants and configuration for the LAN Video Calling Application
"""

# Network Configuration
DEFAULT_SERVER_PORT = 8888
DEFAULT_VIDEO_PORT = 8889
DEFAULT_AUDIO_PORT = 8890
DEFAULT_FILE_PORT = 8891
DEFAULT_CHAT_PORT = 8892

# Buffer Sizes
VIDEO_BUFFER_SIZE = 65536
AUDIO_BUFFER_SIZE = 4096
FILE_BUFFER_SIZE = 8192
CHAT_BUFFER_SIZE = 1024

# Message Types
class MessageType:
    # Connection
    CONNECT = "CONNECT"
    DISCONNECT = "DISCONNECT"
    HEARTBEAT = "HEARTBEAT"
    
    # User Management
    USER_JOIN = "USER_JOIN"
    USER_LEAVE = "USER_LEAVE"
    USER_LIST = "USER_LIST"
    
    # Room Management
    ROOM_CREATE = "ROOM_CREATE"
    ROOM_JOIN = "ROOM_JOIN"
    ROOM_LEAVE = "ROOM_LEAVE"
    ROOM_LIST = "ROOM_LIST"
    
    # Video/Audio
    VIDEO_FRAME = "VIDEO_FRAME"
    AUDIO_FRAME = "AUDIO_FRAME"
    VIDEO_START = "VIDEO_START"
    VIDEO_STOP = "VIDEO_STOP"
    AUDIO_START = "AUDIO_START"
    AUDIO_STOP = "AUDIO_STOP"
    SCREEN_SHARE = "SCREEN_SHARE"
    
    # Chat
    CHAT_MESSAGE = "CHAT_MESSAGE"
    CHAT_HISTORY = "CHAT_HISTORY"
    
    # File Transfer
    FILE_UPLOAD_START = "FILE_UPLOAD_START"
    FILE_UPLOAD_CHUNK = "FILE_UPLOAD_CHUNK"
    FILE_UPLOAD_END = "FILE_UPLOAD_END"
    FILE_DOWNLOAD_REQUEST = "FILE_DOWNLOAD_REQUEST"
    FILE_DOWNLOAD_CHUNK = "FILE_DOWNLOAD_CHUNK"
    FILE_DOWNLOAD_END = "FILE_DOWNLOAD_END"
    FILE_LIST = "FILE_LIST"
    FILE_DELETE = "FILE_DELETE"
    
    # Meeting Controls
    MUTE_USER = "MUTE_USER"
    UNMUTE_USER = "UNMUTE_USER"
    KICK_USER = "KICK_USER"
    RECORDING_START = "RECORDING_START"
    RECORDING_STOP = "RECORDING_STOP"
    
    # Host Controls
    MEETING_CONTROL = "MEETING_CONTROL"
    MEETING_STATE = "MEETING_STATE"
    HOST_NOTIFICATION = "HOST_NOTIFICATION"
    KICK = "KICK"
    MUTE_PARTICIPANT = "MUTE_PARTICIPANT"
    UNMUTE_PARTICIPANT = "UNMUTE_PARTICIPANT"
    
    # Response Types
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    ACK = "ACK"

# Video Configuration
VIDEO_WIDTH = 640
VIDEO_HEIGHT = 480
VIDEO_FPS = 30
VIDEO_QUALITY = 80

# Audio Configuration
AUDIO_SAMPLE_RATE = 44100
AUDIO_CHANNELS = 2
AUDIO_CHUNK_SIZE = 1024

# File Transfer
MAX_FILE_SIZE = 100 * 1024 * 1024  # 100MB
CHUNK_SIZE = 8192
UPLOAD_DIR = "uploads"
DOWNLOAD_DIR = "downloads"

# Timeouts
CONNECTION_TIMEOUT = 30
HEARTBEAT_INTERVAL = 5
RECONNECT_ATTEMPTS = 3

# GUI Configuration
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
THEME_COLOR = "#1f538d"
